# Generated by Django 5.2.7 on 2025-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_add_book", "Can add a new book"),
                    ("can_change_book", "Can edit existing book details"),
                    ("can_delete_book", "Can delete a book record"),
                ]
            },
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
