# Generated by Django 5.2.7 on 2025-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="extra_notes",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
